import './globals.css'
import {ReactNode} from "react";
import {Header} from "../src/components/client/molecules/Header";
import {Footer} from "../src/components/client/atoms/Footer";

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Next13 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
      <Header/>
      <main style={{paddingTop:'100px'}}>
        {children}
      </main>
      <Footer/>
      </body>
    </html>
  )
}